import os, sys, tempfile, shutil
sys.path.insert(0, os.getcwd())
from import_tracker.index import IncrementalIndex
work = tempfile.mkdtemp()
pkg = os.path.join(work, 'mylib')
os.makedirs(os.path.join(pkg, 'sub'))
def w(rel, text):
    with open(os.path.join(pkg, rel), 'w', encoding='utf-8') as f: f.write(text)
w('__init__.py', 'import os\nfrom .sub import a\n')
w('sub/__init__.py', 'from . import mod\n')
w('sub/mod.py', 'import json as j\nimport json as json2\nfrom .. import sub\nfrom .... import nope\ntry:\n    import yaml\nexcept ImportError:\n    pass\n')
idx = IncrementalIndex(pkg, 'mylib')
idx.cold_start()
print('verify cold:', idx.verify_against_full_rescan())
os.remove(os.path.join(pkg,'sub','mod.py'))
idx.apply_changes([os.path.join(pkg,'sub','mod.py')])
print('verify delete:', idx.verify_against_full_rescan())
w('sub/mod.py', 'import csv\n')
idx.apply_changes([os.path.join(pkg,'sub','mod.py')])
print('verify recreate:', idx.verify_against_full_rescan())
for n in range(5):
    w('sub/mod.py', f'import time as t{n}\n')
    idx.apply_changes([os.path.join(pkg,'sub','mod.py')])
print('verify repeated edits:', idx.verify_against_full_rescan())
w('sub/mod.py', 'def broken(:\n')
idx.apply_changes([os.path.join(pkg,'sub','mod.py')])
s = idx.snapshot()
print('stale:', s['groups']['mylib.sub.mod']['stale'], 'retained:', s['groups']['mylib.sub.mod']['imports'])
print('verify stale:', idx.verify_against_full_rescan())
w('sub/mod.py', 'import csv\n')
idx.apply_changes([os.path.join(pkg,'sub','mod.py')])
print('verify recovered:', idx.verify_against_full_rescan())
shutil.rmtree(os.path.join(pkg,'sub'))
idx.apply_changes([os.path.join(pkg,'sub','__init__.py'), os.path.join(pkg,'sub','mod.py')])
print('verify dir delete:', idx.verify_against_full_rescan())
os.makedirs(os.path.join(pkg,'sub'))
w('sub/__init__.py','import sys\n')
w('sub/mod.py','import os\n')
idx.apply_changes([os.path.join(pkg,'sub','__init__.py'), os.path.join(pkg,'sub','mod.py')])
print('verify recreated pkg:', idx.verify_against_full_rescan())
shutil.rmtree(work)
